### ISSUE TITLE
2.4.0的sdk NullPointerException

### ISSUE THREAD

**Issue by NormanOu** [mobileresearch/weibo_android_sdk#57]
使用sso授权登录，但是没有安装微博客户端的时候，授权的webview可以正常出来，输入用户名密码点击确定后就抛出这样的异常
java.lang.NullPointerException
at com.sina.weibo.sdk.auth.WeiboDialog$WeiboWebViewClient.onPageFinished(WeiboDialog.java:336)
at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:449)
at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:70)

**Comment by mobileresearch** [comment]
@NormanOu 感谢您的反馈。我刚刚测试了一下，没有发现这个问题，但我猜测到问题出在哪里了。能否告知一下你测试的机器的各项配置？如系统版本、内存大小等参数。谢谢。

**Comment by NormanOu** [comment]
@mobileresearch 
使用的是模拟器 android4.4
AVD_for_3_2in_HVGA_slider_ADP1

**Comment by mobileresearch** [comment]
@NormanOu 好的。你在手机上试过了吗？有没有同样的问题？

**Comment by NormanOu** [comment]
@mobileresearch 还没在真机上测试过。另外这个bug不是必现的，在模拟器上是偶发，但是概率很高。

**Comment by mobileresearch** [comment]
@NormanOu 好的，我知道了。谢谢。后续Bug修正过程我将会在这里进行反馈。

**Comment by liyunfan** [comment]
在低内存机器上SSO登录，onActivityResult时可能activity已经被销毁，这时mSsoHandler就为null了。建议接口增加setAuthDialogListener的接口，这样如果mSsoHandler为null，我们就新创建一个mSsoHandler，同时setAuthDialogListener，现在setAuthDialogListener跟authorize绑定在一起是非常不合理的。

**Comment by LuJason** [comment]
我现在也遇到了同样的问题，请问应该如何解决的啊？
